name: nblosum
channels:
  - conda-forge
  - anaconda
  - plotly
dependencies:
  - python=3.11
  - pip=21.2.4
  - plotly=5.15
  - pandas=2.0.3
  - pytest=7.4.0
  - scikit-learn=1.2.2
  - networkx=3.1
  - numpy=1.25.2
  - tqdm=4.65.0
  - pip:
    - biopython==1.81
