name: nblosum
channels:
  - conda-forge
  - anaconda
  - plotly
dependencies:
  - requests=2.31.0
  - python=3.11
  - plotly=5.15
  - pandas=2.0.3
  - nbformat=5.7.0
  - matplotlib=3.5.2
  - pip:
    - biopython==1.81
    - tikzplotlib==0.10.1
